version: 2

jobs:
  test_python2:
    docker:
      - image: circleci/python:2.7.15

    steps:
      - checkout
      - run: sudo apt-get update -qy
      - run: sudo apt-get install -qy python-virtualenv
      - restore_cache:
          keys:
          - dependencies-p2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install test runner
          command: |
            . venv/bin/activate
            pip install nose
      - save_cache:
          paths:
            - ./venv
          key: dependencies-p2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests -v

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test_python3:
    docker:
      - image: circleci/python:3.6.5

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-p3-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install test runner
          command: |
            . venv/bin/activate
            pip install nose
      - save_cache:
          paths:
            - ./venv
          key: dependencies-p3-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            nosetests -v

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  tests:
    jobs:
      - test_python2
      - test_python3
